### ISSUE TITLE
DRE - RF01 - Cadastrar Usuário

### ISSUE THREAD

**Issue by LucasLamounierD** [ClayBueno/ProjetoCrossfit#2]
No _RF01 - Cadastrar usuário_ o campo de cadastro referente ao sexo não está definido como obrigatório, porém no _RF18 - Gerar Relatório dos melhores alunos por nível e de exercício_ há um filtro para seleção de canditados relativos aos seus sexos, caso um usuário seja cadastrado sem o sexo (que está como não obrigatório) o relatório provavelmente virá com falhas.

**Comment by ander-oliveira** [comment]
Resolvido
