### ISSUE TITLE
DRE - Preechimento irregular de seções.

### ISSUE THREAD

**Issue by rodrigoaasm** [ClayBueno/ProjetoCrossfit#3]
Os requesitos funcionais de sistema foram chamado apenas de RF sendo que no template são chamados de RFS. 
Erro na formatação do arquivo, existe uma quebra de linha a mais ou não, após os atores nas seções dos RFSs?  Pois algumas apresentam e outras não.

**Comment by ander-oliveira** [comment]
Resolvido
